// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace IELTS_PTE.DataAccess
{
    public partial class IELTS_PTEContext : DbContext
    {
        public IELTS_PTEContext()
        {
        }

        public IELTS_PTEContext(DbContextOptions<IELTS_PTEContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ApplicationUser> ApplicationUser { get; set; }
        public virtual DbSet<ListeningFillInBlanks> ListeningFillInBlanks { get; set; }
        public virtual DbSet<ListeningHighlightCorrectSummary> ListeningHighlightCorrectSummary { get; set; }
        public virtual DbSet<ListeningHighlightIncorrectWords> ListeningHighlightIncorrectWords { get; set; }
        public virtual DbSet<ListeningListeningMultipleChoice> ListeningListeningMultipleChoice { get; set; }
        public virtual DbSet<ListeningListeningSingleChoice> ListeningListeningSingleChoice { get; set; }
        public virtual DbSet<ListeningSelectMissingWord> ListeningSelectMissingWord { get; set; }
        public virtual DbSet<ListeningSummariesSpokenText> ListeningSummariesSpokenText { get; set; }
        public virtual DbSet<ListeningWriteFromDictation> ListeningWriteFromDictation { get; set; }
        public virtual DbSet<ReadingFillingTheBlank> ReadingFillingTheBlank { get; set; }
        public virtual DbSet<ReadingQuestions> ReadingQuestions { get; set; }
        public virtual DbSet<ReadingReOrderParagraph> ReadingReOrderParagraph { get; set; }
        public virtual DbSet<ReadingReadingMultipleChoice> ReadingReadingMultipleChoice { get; set; }
        public virtual DbSet<ReadingReadingSingleChoice> ReadingReadingSingleChoice { get; set; }
        public virtual DbSet<ReadingReadingWritingFillInTheBlank> ReadingReadingWritingFillInTheBlank { get; set; }
        public virtual DbSet<SpeakingAnswerShort> SpeakingAnswerShort { get; set; }
        public virtual DbSet<SpeakingDescribeImage> SpeakingDescribeImage { get; set; }
        public virtual DbSet<SpeakingReTellLecture> SpeakingReTellLecture { get; set; }
        public virtual DbSet<SpeakingReadAloud> SpeakingReadAloud { get; set; }
        public virtual DbSet<SpeakingRepeatSentence> SpeakingRepeatSentence { get; set; }
        public virtual DbSet<SpeakingRepeatSentenceReview> SpeakingRepeatSentenceReview { get; set; }
        public virtual DbSet<SystemConfig> SystemConfig { get; set; }
        public virtual DbSet<WritingEssay> WritingEssay { get; set; }
        public virtual DbSet<WritingSummariseWrittenText> WritingSummariseWrittenText { get; set; }
        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<ApplicationUser>(entity =>
            {
                entity.HasKey(e => e.UserId)
                    .HasName("PK_AppUser");
            });

            modelBuilder.Entity<SystemConfig>(entity =>
            {
                entity.HasIndex(e => e.Code)
                    .HasName("IX_SystemConfig")
                    .IsUnique();

                entity.Property(e => e.CreatedBy).HasDefaultValueSql("(suser_sname())");

                entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getutcdate())");

                entity.Property(e => e.UpdatedBy).HasDefaultValueSql("(suser_sname())");

                entity.Property(e => e.UpdatedDate).HasDefaultValueSql("(getutcdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}