// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IELTS_PTE.DataAccess
{
    public partial class ReadingQuestions
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string FillInTheBlanks { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Questiontime { get; set; }
        public bool IsFree { get; set; }
        public int QuestionType { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
}