USE [master]
GO
/****** Object:  Database [IELTS_PTE]    Script Date: 7/16/2019 6:11:34 PM ******/
CREATE DATABASE [IELTS_PTE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IELTS_PTE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\IELTS_PTE.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IELTS_PTE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\IELTS_PTE_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [IELTS_PTE] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IELTS_PTE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [IELTS_PTE] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IELTS_PTE] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IELTS_PTE] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IELTS_PTE] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IELTS_PTE] SET ARITHABORT OFF 
GO
ALTER DATABASE [IELTS_PTE] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [IELTS_PTE] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IELTS_PTE] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IELTS_PTE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IELTS_PTE] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IELTS_PTE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IELTS_PTE] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IELTS_PTE] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IELTS_PTE] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IELTS_PTE] SET  ENABLE_BROKER 
GO
ALTER DATABASE [IELTS_PTE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IELTS_PTE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IELTS_PTE] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [IELTS_PTE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [IELTS_PTE] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IELTS_PTE] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [IELTS_PTE] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [IELTS_PTE] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [IELTS_PTE] SET  MULTI_USER 
GO
ALTER DATABASE [IELTS_PTE] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IELTS_PTE] SET DB_CHAINING OFF 
GO
ALTER DATABASE [IELTS_PTE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [IELTS_PTE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [IELTS_PTE] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [IELTS_PTE] SET  READ_WRITE 
GO
